### ISSUE TITLE
test01_maximum(), test02_minimum() comparators

### ISSUE THREAD

**Issue by volhovM** [kgeorgiy/java-advanced-2015#10]

**Comment by kgeorgiy** [comment]
Что это было?

**Comment by volhovM** [comment]
Извиняюсь, я по ошибке сначала добавил пустое ишью (форма по <Enter> делает не то, что предполагается). Теперь там есть описание, собственно.

**Comment by kgeorgiy** [comment]
Для компаратора `AllEqual` правильным результатом будет только первый элемент. С формальной точки зрения, для проверки этого стоило использовать `==`, но ожидаемый эффект достигается и без этого.
