### ISSUE TITLE
HyperThreading

### ISSUE THREAD

**Issue by CoolGirl** [kgeorgiy/java-advanced-2015#11]
У меня четырехъядерный процессор с HyperThreading, соответственно, 

     System.out.println(Runtime.getRuntime().availableProcessors()); 

возвращает восемь, но при этом реального прироста по сравнению с однопоточным исполнением достичь в 8/1.5=5 раз не удаётся (максимальный результат 4.7). Ожидаемый прирост на этом процессоре действительно равен 4*1.2 и  не превышает пяти.

**Comment by kgeorgiy** [comment]
2015-03-19 3:25 GMT+03:00 CoolGirl <notifications@github.com>:

> возвращает восемь, но при этом реального прироста по сравнению с
> однопоточным исполнением достичь в 8/1.5=5 раз не удаётся (максимальный
> результат 4.7). Ожидаемый прирост на этом процессоре действительно равен
> 4*1.2 и не превышает пяти.
>
> Вообще говоря, прирост от HyperThreading должен быть больше чем 20%



-- 
С уважением, Георгий Корнеев
