### ISSUE TITLE
Метод close у интерфейса ParallelMapper

### ISSUE THREAD

**Issue by pva701** [kgeorgiy/java-advanced-2015#12]
Что должен делать этот метод, если в данный момент происходит выполнение метода run() для какого-то потока? Сразу останавливать выполнение? И что возвращать стоящим в очереди потокам при вызове этого метода?

P.S. Видимо разумнее всего будет бросать исключение InterruptedException всем, кто сейчас выполняется и стоит в очередь на выполнение?

**Comment by kgeorgiy** [comment]
Ответ на этот вопрос является частью задания.

2015-03-21 22:59 GMT+03:00 Peresadin Ilya <notifications@github.com>:

> Что должен делать этот метод, если в данный момент происходит выполнение
> метода run() для какого-то потока? Сразу останавливать выполнение? И что
> возвращать стоящим в очереди потокам при вызове этого метода?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kgeorgiy/java-advanced-2015/issues/12>.
>



-- 
С уважением, Георгий Корнеев
