### ISSUE TITLE
Hometask #8

### ISSUE THREAD

**Issue by sultanko** [kgeorgiy/java-advanced-2015#14]
1) Нужно делать 8 задание к четвергу(9.04)?
2) Можно ли в нем использовать ThreadPool, BlockingQueue из java.util.concurrent или предполагается использование предыдущего домашнего задания?
3) Будет ли в четверг(09.04) лекция?

**Comment by kgeorgiy** [comment]
2015-04-06 22:04 GMT+03:00 Shah Egor <notifications@github.com>:

> 2) Можно ли в нем использовать ThreadPool, BlockingQueue из
> java.util.concurrent или предполагается использование предыдущего домашнего
> задания?
>
> 1) Да
2) Можно использовать Concurrency Utilities



-- 
С уважением, Георгий Корнеев

**Comment by sultanko** [comment]
В обновленных тестах к WebCrawler при скачке http://acm.tuit.uz, http://validator.w3.org/check?uri=referer, http://www.kgeorgiy.info/courses/alg-intro/statements/intersec.tex выбрасывается IOException. Если это исключение не ловить, то тесты не проходят, а если ловить, то нет. Это баг или фича?

**Comment by kgeorgiy** [comment]
>
> то исключение не ловить, то тесты не проходят, а если ловить, то нет


Что-что?


-- 
С уважением, Георгий Корнеев

**Comment by sultanko** [comment]
Если исключение при загрузке страницы проигнорировать, то тесты проходят. А если это исключение выкинуть из метода download, то не проходят.

**Comment by kgeorgiy** [comment]
2015-04-29 19:03 GMT+03:00 Shah Egor <notifications@github.com>:

> Если исключение при загрузке страницы проигнорировать, то тесты проходят.
> А если это исключение выкинуть из метода download, то не проходят.
>
Все правильно


-- 
С уважением, Георгий Корнеев

**Comment by sultanko** [comment]
То есть если у нас произошла ошибка(например отсутсвует соединение), то пользователю мы ничего не скажем, а просто вернем пустой список?

**Comment by kgeorgiy** [comment]
Теперь вы дополнительно вернете набор ошибок.

2015-04-30 0:33 GMT+03:00 Shah Egor <notifications@github.com>:

> То есть если у нас произошла ошибка(например отсутсвует соединение), то
> пользователю мы ничего не скажем, а просто вернем пустой список?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kgeorgiy/java-advanced-2015/issues/14#issuecomment-97592325>
> .
>



-- 
С уважением, Георгий Корнеев
