### ISSUE TITLE
Тесты к HelloUDP

### ISSUE THREAD

**Issue by knah** [kgeorgiy/java-advanced-2015#16]
В тестах к серверу наблюдается неприятный спецэффект - совершенно рандомно вылетает BindException. Из внимательного чтения своего кода и кода тестов я пришел к единственному выводу - после закрытия сокета система не сразу же считает порт, на который был сделан бинд, свободным. В результате при быстром пересоздании сокета на одном порте есть ненулевая вероятность неудачи.
Хотелось бы поправить, например в каждом тесте создавать сервер на уникальном порту.

**Comment by knah** [comment]
Также хочу заметить, что исходный код тестов не компилируется и не соответствует коду, находящемуся в HelloUDPTest.jar. Как-то это нехорошо.

**Comment by kgeorgiy** [comment]
2015-04-29 17:09 GMT+03:00 Nikolay Kuznetsov <notifications@github.com>:

> Также хочу заметить, что исходный код тестов не компилируется и не
> соответствует коду, находящемуся в HelloUDPTest.jar. Как-то это нехорошо.
>

А как именно не компилируется? И под какой версией JDK?

.jar-файлы перевыложил.



-- 
С уважением, Георгий Корнеев

**Comment by knah** [comment]
Не компилируется оно под любым JDK с ошибкой "HelloClientTest.java:58: error: cannot find symbol ... Util.server(String, int, double, DatagramSocket)".
Содержимое .jar все еще не соответствует исходникам. При декомпиляции видно отсутствие вызова метода Util.server, и создается ощущение того, что javac научился инлайнить методы.
В самом Util данного метода тоже не наблюдается. Исходного кода класса Util не приложено.

**Comment by kgeorgiy** [comment]
Перевыложил Util.class и .jar

2015-04-29 18:46 GMT+03:00 Nikolay Kuznetsov <notifications@github.com>:

> Не компилируется оно под любым JDK с ошибкой "HelloClientTest.java:58:
> error: cannot find symbol ... Util.server(String, int, double,
> DatagramSocket)".
> Содержимое .jar все еще не соответствует исходникам. При декомпиляции
> видно отсутствие вызова метода Util.server, и создается ощущение того, что
> javac научился инлайнить методы.
> В самом Util данного метода тоже не наблюдается. Исходного кода класса
> Util не приложено.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kgeorgiy/java-advanced-2015/issues/16#issuecomment-97475874>
> .
>



-- 
С уважением, Георгий Корнеев
