### ISSUE TITLE
Тесты ко второму домашнему заданию

### ISSUE THREAD

**Issue by vadimsemenov** [kgeorgiy/java-advanced-2015#3]
Выложите ли Вы сабж?

**Comment by kgeorgiy** [comment]
Выложил

On 24 February 2015 at 20:04, Vadim Semenov <notifications@github.com>
wrote:

> Выложите ли Вы сабж?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kgeorgiy/java-advanced-2015/issues/3>.
>



-- 
С уважением, Георгий Корнеев
