### ISSUE TITLE
Java version

### ISSUE THREAD

**Issue by volhovM** [kgeorgiy/java-advanced-2015#6]
Какая версия языка должна поддерживаться в домашнем задании #3 по теме Reflection?

**Comment by kgeorgiy** [comment]
В Reflection API со времен Java 5 не было существенных изменений. Дополнения к JLS 3 не отражаются на Reflection API.
Видимо, вы имеете ввиду какую-то конкретную проблему, но я не понимаю, какаю.

**Comment by volhovM** [comment]
Я могу предполагать, что в java8 кроме дефолтных и еще каких-то методов в интерфейсах появилось еще нечто, о чем я не знаю, поэтому и спрашиваю. Конкретно разница между 1.7 и 1.8.

**Comment by kgeorgiy** [comment]
В соответствии с http://docs.oracle.com/javase/8/docs/technotes/guides/reflection/enhancements.html, единственное изменение в Reflection API между Java 7 и Java 8 -- возможность доступа к именам аргументов методов.
