### ISSUE TITLE
Некорректный тест 06_burnPerformance

### ISSUE THREAD

**Issue by knah** [kgeorgiy/java-advanced-2015#9]
Вероятно, предполагалось, что 8 потоков, ждущие по 10мс каждый на 4 ядрах суммарно выполняются за 20мс. Однако, это предположение не всегда корректно.
При достаточно быстром планировщике, возможно выполнение 8 "медленных" компараторов за 10мс. Достигается это таким образом: при достаточно быстром переключении между потоками, все восемь потоков могут почти одновременно войти в компараторы, засечь почти одинаковое начало выполнения, проработать 10 реальных мс и коллективно выйти из компаратора.
Нужно с этим что-нибудь сделать, например изменить метод ожидания с "ждать 10 мс" на "провести N итераций цикла". При таком компараторе быстрый планировщик не даст никакого преимущества.

**Comment by kgeorgiy** [comment]
Fixed

**Comment by knah** [comment]
А еще не хватает обновленного .jar-файла с тестами.

**Comment by kgeorgiy** [comment]
Сделайте сами

**Comment by sultanko** [comment]
А можете поподробнее рассказать про обновление подписанного jar файла и генерацию digest sha256? Я так и не понял как это сделать из документации.

**Comment by kgeorgiy** [comment]
2015-03-18 21:12 GMT+03:00 Shah Egor <notifications@github.com>:

> А можете поподробнее рассказать про обновление подписанного jar файла и
> генерацию digest sha256? Я так и не понял как это сделать из документации.
>
А зачем вам подписанный jar-файл? Все равно, завтра будут новые.



-- 
С уважением, Георгий Корнеев

**Comment by sultanko** [comment]
Потому что если не совпадают sha256 суммы, то запустить тесты нельзя. А хотелось бы проверить на новых.

**Comment by kgeorgiy** [comment]
2015-03-18 21:15 GMT+03:00 Shah Egor <notifications@github.com>:

> Потому что если не совпадают sha256 суммы, то запустить тесты нельзя.
>
 Как это?


-- 
С уважением, Георгий Корнеев

**Comment by sultanko** [comment]
Ну это если заморачиваться с обновлением исходного jar файла. Но я нашел почему просто jar файл не генерился, из-за дополнительного класса в base. Вопрос снят.

**Comment by kgeorgiy** [comment]
2015-03-18 21:25 GMT+03:00 Shah Egor <notifications@github.com>:

> Ну это если заморачиваться с обновлением исходного jar файла. Но я нашел
> почему просто jar файл не генерился, из-за дополнительного класса в base.
> Вопрос снят.
>
Зачем вообще для запуска тестов генерировать .jar-файл??


-- 
С уважением, Георгий Корнеев

**Comment by sultanko** [comment]
Чтобы не менять скрипт запуска + я думал что это не сложно.
